// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHml1YIliy7ljFsPQFf7S_25m8jLJZWvc',
    appId: '1:416788351953:web:eb464c357ba32b758a6ef0',
    messagingSenderId: '416788351953',
    projectId: 'floricultura-mobile',
    authDomain: 'floricultura-mobile.firebaseapp.com',
    storageBucket: 'floricultura-mobile.appspot.com',
    measurementId: 'G-Q9994VRMY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_lLLH7_fswAcHOIOvb_ZpOB6lVJ6izQ',
    appId: '1:416788351953:android:3f0e6b0f734c98d28a6ef0',
    messagingSenderId: '416788351953',
    projectId: 'floricultura-mobile',
    storageBucket: 'floricultura-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5p9-uZerNE2GTng0LmmlBUTw6tkZN-84',
    appId: '1:416788351953:ios:200a25f2e042c1958a6ef0',
    messagingSenderId: '416788351953',
    projectId: 'floricultura-mobile',
    storageBucket: 'floricultura-mobile.appspot.com',
    iosClientId: '416788351953-jktpvg7pgoe0csa6dr12mshneh3q7hcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.floricultura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5p9-uZerNE2GTng0LmmlBUTw6tkZN-84',
    appId: '1:416788351953:ios:200a25f2e042c1958a6ef0',
    messagingSenderId: '416788351953',
    projectId: 'floricultura-mobile',
    storageBucket: 'floricultura-mobile.appspot.com',
    iosClientId: '416788351953-jktpvg7pgoe0csa6dr12mshneh3q7hcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.floricultura',
  );
}
